version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amazon-cognito-react-amplify"
s3_bucket = ""
s3_prefix = "amazon-cognito-react-amplify"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
